# Robot drive and mechanical parameters
Drive Type: "ArlobotDifferential"
Track Width: 0.4030 # meter
Tick Per Revolution: 72
Wheel Diameter: 0.1524 # meter

# Speed constraints
Max Linear Speed: 1.0 # meter/sec
Max Angular Speed: 1.0 # rad/sec

# Node parameters
Base Node Loop Rate: 1
Drive Node Loop Rate: 10
Sensors Node Loop Rate: 10
Diff Drive Loop Rate: 10

# HAL parameters
HAL Service Timeout Rate: 1
HAL Simulate: True
I2C Device: 1
Left Psoc4 I2C Address: 0x08
Right Psoc4 I2C Address: 0x09
IMU Mag I2C Address: 0x1e
IMU Acc I2C Address: 0x1d
Power Pi AVR I2C Address: 0x21
Power Pi INA219 I2C Address: 0x40
XV11 Port: "/dev/ttyUSB0"
XV11 Baud: 115200

# Drive Control
Drive Node Gains: {"kp" : 1.0, "ki" : 0.1, "kd" : 0.01}

# Sensors Parameters
# I was thinking about either an enable/disable for each sensor type or maybe just control over publishing.  There is no
# specific need here at the moment.
